@startuml Domain Model
skinparam DefaultFontName Inter
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ArrowThickness 1
hide empty members

object "Hero" as Main_Character {
  - equippedItem
  - inventory
}
object Game{
}
object Player{
}
object Landscape_Entity{
   -LandscapeInteraction
}
object Entity {
  - health
  - power
  - score
  - weight
}
object Action{
  -talk to [NPC]
  -exit
  -attack [NPC]
  -move [direction]
  -inspect [Item]
  -view inventory
  -examine landscape
  -look around
  -load
  -save

}
object Item {
  - name
  - damage 
  - weight 
  - score
}
object NPC {
  -NPCInteraction
}
object Pyramid {
}
object Room {
   - walls
}
Room "1"-- "1..*" Item : contains >
Pyramid "1"*--"1..*" Room: contains >
Room "1"*-- "1..*" NPC : contains >
Game "1"--"1" Pyramid: played on
Main_Character "1"--"*" Item: owns >
Entity -- Main_Character: is a <
NPC -- Entity: is a >
Landscape_Entity -- Entity: is a >
Landscape_Entity "*"--*"1" Room: contains <
Main_Character "1" -- "1" Room: is on
Player "1"--"1" Main_Character: controls
Player -- Game: plays
Player "1"--"1..*" Action: chooses
Main_Character "1"--"1..*" Action: executes
Action -- Game: interacts
Action -- NPC: interacts
Action -- Landscape_Entity: interacts
Action -- Item: interacts

@enduml
