@startuml Domain Model
skinparam DefaultFontName Inter
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ArrowThickness 1
hide empty members

object "Player" as Main_Character {
  equippedItem
}
object Entity
object Attack
object Talk
object Item {
  name
  damage 
  weight 
  score
}
object NPC 
object Pyramid 
object Room {
  walls
}

Entity -- "*" Main_Character : is-a <
Entity -- "*" NPC : is-a <
Main_Character -- Room : is-in >
Main_Character -- "*" Item : has >
(Main_Character,NPC) .. Attack
(Main_Character,NPC) .. Talk
Room -- "*" Item : contains >
Room -- "1" NPC : hosts >
Room --> "*" Room : can-have
Pyramid "1" -- "9" Room : has >
@enduml

