@startuml Domain Model
skinparam DefaultFontName Inter
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ArrowThickness 1
hide empty members

object "Player" as Main_Character {
  - equippedItem
}
object Entity {
  - health
  - power
}
object Attack
object Talk
object Item {
  - name
  - damage 
  - weight 
  - score
}
object NPC 
object Pyramid {
  - rooms
}
object Room 

Entity -- "*" Main_Character : is-a <
Entity -- "*" NPC : is-a <
Main_Character -- Room : is-in >
Main_Character -- "*" Item : equips >
(Main_Character,NPC) .. Attack
(Main_Character,NPC) .. Talk
Room -- "*" Item : contains >
Room .. "1" NPC : could hosts >
Pyramid "1" -- "9" Room : has >

Main_Character -[hidden]down- Room
Entity -[hidden]left- Main_Character
Pyramid -[hidden]up- Room

@enduml
